import React from 'react';
import { X, Download, Code, Monitor, Smartphone } from 'lucide-react';

interface DesignPreviewModalProps {
  htmlCode: string;
  onClose: () => void;
}

const DesignPreviewModal: React.FC<DesignPreviewModalProps> = ({ htmlCode, onClose }) => {
  const [viewMode, setViewMode] = React.useState<'desktop' | 'mobile'>('desktop');

  const handleDownload = () => {
    const blob = new Blob([htmlCode], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'improved-design.html';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[60] bg-slate-100 dark:bg-slate-900 flex flex-col animate-fade-in transition-colors">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 shrink-0 transition-colors">
          <div className="flex items-center gap-4">
            <div className="bg-indigo-600 p-2 rounded-lg">
              <Code className="text-white" size={20} />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 dark:text-white text-lg">Iterated Design Concept</h3>
              <p className="text-xs text-slate-500 dark:text-slate-400">Generated by AI • Tailwind CSS</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            {/* View Toggles */}
            <div className="hidden sm:flex bg-slate-100 dark:bg-slate-900 p-1 rounded-lg border border-slate-200 dark:border-slate-700 mr-4 transition-colors">
              <button
                onClick={() => setViewMode('desktop')}
                className={`p-2 rounded-md transition-colors ${
                  viewMode === 'desktop' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-white shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
                title="Desktop View"
              >
                <Monitor size={18} />
              </button>
              <button
                onClick={() => setViewMode('mobile')}
                className={`p-2 rounded-md transition-colors ${
                  viewMode === 'mobile' ? 'bg-white dark:bg-slate-700 text-indigo-600 dark:text-white shadow-sm' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
                title="Mobile View"
              >
                <Smartphone size={18} />
              </button>
            </div>

            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-colors text-sm shadow-md"
            >
              <Download size={16} /> Download HTML
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-slate-100 dark:hover:bg-slate-700 rounded-full text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white transition-colors"
            >
              <X size={24} />
            </button>
          </div>
        </div>

        {/* Preview Area */}
        <div className="flex-1 bg-slate-200 dark:bg-slate-950 relative flex items-center justify-center overflow-hidden transition-colors">
           <div className={`transition-all duration-500 ease-in-out bg-white shadow-2xl overflow-hidden ${
             viewMode === 'mobile' 
               ? 'w-[375px] h-[812px] max-h-[90vh] rounded-[3rem] border-[8px] border-slate-800' 
               : 'w-full h-full'
           }`}>
             <iframe
               title="Design Preview"
               srcDoc={htmlCode}
               className="w-full h-full border-0"
               sandbox="allow-scripts"
             />
           </div>
        </div>
    </div>
  );
};

export default DesignPreviewModal;